name: flutter_custom_toast
description: "A Flutter package to display customizable toasts without requiring context."
version: 0.0.1
homepage: https://github.com/Matheus-hora48/flutter_custom_toast
repository: https://github.com/Matheus-hora48/flutter_custom_toast

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


